### ISSUE TITLE
Signor test failing due to complex members

### ISSUE THREAD

**Issue by bgyori** [sorgerlab/indra#804]
It appears that the members of a complex we test has changed causing a test to fail:
```
======================================================================
FAIL: indra.tests.test_signor.test_parse_csv_from_web
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/travis/build/sorgerlab/indra/indra/tests/test_signor.py", line 63, in test_parse_csv_from_web
    assert sp.complex_map['SIGNOR-C1'] == ['P23511', 'P25208', 'Q13952']
AssertionError: 
```
Depending on the underlying cause, we may need to fix the test or the processor.

**Comment by bgyori** [comment]
Fixed in #806

**Comment by kkaris** [comment]
I see errors still on this in some of the logs. It's a bug introduced by me. _This is fixed by PR https://github.com/sorgerlab/indra/pull/815_
